// config/shortcuts.ts
export const keyboardShortcuts = [
  { keys: ["⌘", "n"], action: "New Email" },
  { keys: ["⌘", "Enter"], action: "Send Email" },
  { keys: ["⌘", "r"], action: "Reply" },
  { keys: ["⌘", "Shift", "r"], action: "Reply All" },
  { keys: ["⌘", "f"], action: "Forward" },
  { keys: ["⌘", "Shift", "d"], action: "Drafts" },
  { keys: ["⌘", "Shift", "i"], action: "Inbox" },
  { keys: ["⌘", "Shift", "s"], action: "Sent Mail" },
  { keys: ["⌘", "Backspace"], action: "Delete" },
  { keys: ["⌘", "/"], action: "Search" },
  { keys: ["⌘", "Shift", "u"], action: "Mark as Unread" },
  { keys: ["⌘", "Shift", "m"], action: "Mute Thread" },
  { keys: ["⌘", "Shift", "p"], action: "Print Email" },
  { keys: ["⌘", "Shift", "h"], action: "Archive Email" },
  { keys: ["⌘", "Shift", "j"], action: "Mark as Spam" },
  { keys: ["⌘", "Shift", "e"], action: "Move to Folder" },
  { keys: ["⌘", "Shift", "t"], action: "Undo Last Action" },
  { keys: ["⌘", "Shift", "v"], action: "View Email Details" },
  { keys: ["⌘", "Shift", "g"], action: "Go to Drafts" },
  { keys: ["⌘", "Shift", "x"], action: "Expand Email View" },
  { keys: ["⌘", "?"], action: "Help with shortcuts" },
];
